import '../styles/globals.css';
import React from 'react';
import Sidebar from 'src/components/Common/Sidebar';
import {
  GENERAL_SIDEBAR_ITEMS,
  MYPAGE_SIDEBAR_ITEMS,
} from 'src/constants/sidebarItems';

export const metadata = {
  title: 'My Next.js App',
  description: 'Generated by create-next-app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body>
        <Sidebar
          isCollapsed
          // sidebarItems={GENERAL_SIDEBAR_ITEMS}
          sidebarItems={MYPAGE_SIDEBAR_ITEMS}
        />
        {children}
      </body>
    </html>
  );
}
